name: Distribute
permissions: 
  contents: write
on:
    push:
        tags:
        - '*'
          
jobs:
  build-windows:
    strategy:
      matrix:
        targetplatform: [ x64 ]
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish
        run: dotnet publish Tobey/Tobey.csproj /p:Configuration=Release /p:PublishProfile=FolderProfile -o publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tobey.exe
          path: publish/Tobey.exe
          
  
  build-linux:
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Publish
        run: dotnet publish Tobey/Tobey.csproj /p:Configuration=Release /p:PublishProfile=FolderProfile -o publish
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tobey
          path: publish/Tobey
          
  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: Tobey.exe
      
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: Tobey
          
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
          files: |
            Tobey.exe
            Tobey