name: PR build test

on:
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Create Build Directory
        run: mkdir build

      - name: Build with CMake
        run: |
          cd build
          cmake -G Ninja \
            -DCMAKE-BUILD-TYPE=Release \
            -DCMAKE_CXX_FLAGS="-Os -s" \
            -DCMAKE_C_FLAGS="-Os -s" \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
            ..
          cmake --build .

      - name: Zip build/tobey
        run: |
          cd build
          zip -r linux_x86.zip tobey

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_x86.zip
          path: build/linux_x86.zip

  build-windows:
    name: Build on Windows (x86)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Create Build Directory
        run: mkdir build

      - name: Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: win32

      - name: Build with CMake
        run: |
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/O2 /EHsc /DNDEBUG" -DCMAKE_C_FLAGS="/O2 /EHsc /DNDEBUG" -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF ..
          cmake --build .

      - name: Zip build/tobey.exe
        run: |
          cd build
          zip -r win_x86.zip tobey.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win_x86.zip
          path: build/win_x86.zip