name: Build, Package, and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
            cmake-version: 3.30.2

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Create Build Directory
        run: mkdir build

      - name: Build with CMake
        run: |
          cd build
          cmake -G Ninja ..
          cmake --build .

      - name: Package distributable
        run: |
          cd build
          cpack -G TGZ .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/*.tar.gz

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Create Build Directory
        run: mkdir build

      - name: Build with CMake
        run: |
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 ..
          cmake --build . --config Release

      - name: Package distributable
        run: |
          cd build
          cpack -G ZIP .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/*.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]

    steps:
      - name: Download Linux build artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: ./artifacts

      - name: Download Windows build artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release of version ${{ github.ref_name }}.
          draft: false
          prerelease: false

      - name: Upload Linux build to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/*.tar.gz
          asset_name: linux-build-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows build to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/*.zip
          asset_name: windows-build-${{ github.ref_name }}.zip
          asset_content_type: application/zip
