name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Create Build Directory
        run: mkdir build

      - name: Build with CMake
        run: |
          cd build
          cmake -G Ninja -DCMAKE-BUILD-TYPE=Release ..
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tobey
          path: build/Tobey

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Create Build Directory
        run: mkdir build

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build with CMake
        run: |
          cd build
          cmake -G Ninja -DCMAKE-BUILD-TYPE=Release ..
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tobey.exe
          path: build/Tobey.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]

    steps:
      - name: Download Linux build artifact
        uses: actions/download-artifact@v4
        with:
          path: tobey
          pattern: tobey*
          merge-multiple: false

      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: tobey.exe
          pattern: tobey*
          merge-multiple: false

      - name: Display
        run: ls -la

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          files: "*"