name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build on Linux (x86)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Create Build Directory
        run: mkdir build

      - name: Build with CMake
        run: |
          cd build
          cmake -G Ninja \
            -DCMAKE-BUILD-TYPE=Release \
            -DCMAKE_CXX_FLAGS="-Os -s" \
            -DCMAKE_C_FLAGS="-Os -s" \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
            ..
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_x86
          path: build/tobey

  build-windows-x86:
    name: Build on Windows (x86)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Create Build Directory
        run: mkdir build

      - name: Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: win32

      - name: Build with CMake
        run: |
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/O2 /EHsc /DNDEBUG" -DCMAKE_C_FLAGS="/O2 /EHsc /DNDEBUG" -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF ..
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win_x86
          path: build/tobey.exe

  build-windows-x64:
    name: Build on Windows (x64)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.30.2

      - name: Create Build Directory
        run: mkdir build

      - name: Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: win64

      - name: Build with CMake
        run: |
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/O2 /EHsc /DNDEBUG" -DCMAKE_C_FLAGS="/O2 /EHsc /DNDEBUG" -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF ..
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win_x64
          path: build/tobey.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ build-linux, build-windows-x86, build-windows-x64 ]

    steps:
      - name: Download Linux build artifact
        uses: actions/download-artifact@v4
        with:
          pattern: linux_x86
          merge-multiple: false

      - name: Zip Linux build artifact
        run: |
          mv linux_x86/tobey .
          zip -r linux_x86.zip tobey

      - name: Download Windows build artifact (x86)
        uses: actions/download-artifact@v4
        with:
          name: win_x86
          pattern: win_x86
          merge-multiple: false

      - name: Zip Windows build artifact (x86)
        run: |
          zip -r win_x86.zip tobey.exe

      - name: Download Windows build artifact (x64)
        uses: actions/download-artifact@v4
        with:
          name: win_x64
          pattern: win_x64
          merge-multiple: false

      - name: Zip Windows build artifact (x64)
        run: |
          zip -r win_x64.zip tobey.exe

      - name: Debug
        run: ls -lh

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
          files: "linux_x86.zip, win_x86.zip, win_x64.zip"